version: "3.8"

services:
    db:
        image: postgres:15
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER: trader
            - POSTGRES_PASSWORD: secret
            - POSTGRES_DB: orderbook
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: